package testclient

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// karateConfigTmpl is the Go template used to render karate-config.js.
// It produces a valid JS function that Karate auto-loads from the working
// directory before each feature run.
var karateConfigTmpl = template.Must(template.New("karate-config").Funcs(template.FuncMap{
	"escapeJS": func(s string) string {
		s = strings.ReplaceAll(s, `\`, `\\`)
		s = strings.ReplaceAll(s, `'`, `\'`)
		return s
	},
}).Parse(`function fn() {
  // generated by gherkin-tester — do not edit
  var config = {
{{- range $k, $v := .Properties}}
    '{{$k}}': '{{escapeJS $v}}',
{{- end}}
  }
  return config
}
`))

// RenderKarateConfig produces the text content of a karate-config.js file
// from the given environment properties.
// An empty or nil map produces a minimal valid config that returns {}.
func RenderKarateConfig(properties map[string]string) (string, error) {
	if properties == nil {
		properties = map[string]string{}
	}
	data := struct{ Properties map[string]string }{Properties: properties}
	var buf bytes.Buffer
	if err := karateConfigTmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render karate-config.js: %w", err)
	}
	return buf.String(), nil
}
